name: Test

on:
  push:
    branches:
      - "main"
      - "5-create-github-workflow"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libcunit1-dev valgrind xsltproc lcov

      - name: Grant Execute Permissions for scripts
        run: |
          chmod +x ./build.sh
          chmod +x ./test.sh

      - name: Run Tests
        if: always() # Always run the tests
        run: ./test.sh

      - name: Upload Test Reports
        if: always() # Ensures the test reports are uploaded regardless of whether the tests fail the build
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./build/test-reports/*

      - name: Upload Coverage Reports
        if: always() # Ensures the coverage report is uploaded regardless of whether the tests fail the build
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./build/coverage-report/*

      - name: Upload Valgrind Reports
        if: always() # Ensures the valgrind reports are uploaded regardless of whether the tests fail the build
        uses: actions/upload-artifact@v4
        with:
          name: valgrind-reports
          path: ./build/valgrind-reports/*